### ISSUE TITLE
Upload 12.0.1 please!

### ISSUE THREAD

**Issue by jashasweejena** [mspvirajpatel/Xcode_Developer_Disk_Images#1]
Could you please upload the 12.0.1 one? Would be a great relief 🙂. Thank you!

**Comment by emp233** [comment]
I need it also!!!

**Comment by mspvirajpatel** [comment]
Please Check it this one. I hope its help for you 
https://github.com/mspvirajpatel/Xcode_Developer_Disk_Images/releases/tag/12.1

**Comment by mspvirajpatel** [comment]
@jashasweejena  Still you need or not?

**Comment by jashasweejena** [comment]
> 
> 
> @jashasweejena @emp233 Still you need or not?

I did not update from 12.0.1 yet. Thank you for the update.
