### ISSUE TITLE
Wrong image for 14.8

### ISSUE THREAD

**Issue by tux-mind** [mspvirajpatel/Xcode_Developer_Disk_Images#20]
It seems that the 14.8 image is for iOS 15.0 according to idevicesyslog:

> MobileStorageMounter[615] <Notice>: System Version Mismatch for /Developer: (System: 14.8 / Image: 15.0)

**Comment by KressAlex** [comment]
I also couldn't get 14.8 to work. What finally worked was downloading 14.7.1 and rename it to 14.8.

**Comment by mspvirajpatel** [comment]
@tux-mind Updated Now

**Comment by yanhuajun** [comment]
你好，你的来信已收到。

**Comment by tux-mind** [comment]
Thank you very much for solving this issue :blush:

**Comment by yanhuajun** [comment]
你好，你的来信已收到。
