### ISSUE TITLE
iOS 15.0 Developer Disk missing from releases tab

### ISSUE THREAD

**Issue by Nythepegasus** [mspvirajpatel/Xcode_Developer_Disk_Images#22]
AltStore's JIT uses this repository for developer disks. Any reason for getting rid of the 15.0 release?

**Comment by yanhuajun** [comment]
你好，你的来信已收到。

**Comment by mspvirajpatel** [comment]
[Uploading 15.0.zip…]()
@Nythepegasus  @yanhuajun

**Comment by yanhuajun** [comment]
你好，你的来信已收到。
