### ISSUE TITLE
Can't use 15.6 disk image

### ISSUE THREAD

**Issue by federicomiralles** [mspvirajpatel/Xcode_Developer_Disk_Images#23]
First of all congrats for the work done!

Now the issue :)

Despite I used the mentioned directory for unzip the `15.6` disk image, I'm not able to select/use it while trying to create a new Simulator (and yes, I've restarted Xcode):
![Screen Shot 2022-08-19 at 13 17 27](https://user-images.githubusercontent.com/53195495/185665112-b9de50e5-a8a1-409f-b810-0009974682b9.png)

Any ideas?

Thanks in advance!

Cheers,

Federico

**Comment by mspvirajpatel** [comment]
This Disk image is support for the External Device only. If you need's for simulator then you check with Download more simulator runtimes... Button if its provided then download and use. otherwise you need to update xCode. @federicomiralles
