### ISSUE TITLE
Could you please add 16.6?

### ISSUE THREAD

**Issue by KvassBoy** [mspvirajpatel/Xcode_Developer_Disk_Images#43]
Hi there, could you please add ios 16.6. I see there is 16.5 but not above. Thank you

**Comment by sashkyn** [comment]
+

**Comment by omnarayan** [comment]
We have used 16.5 image on 16.6 phones and pads and its working,  Seems there is no change from 16.4.3 one, all images are same.

**Comment by mspvirajpatel** [comment]
https://github.com/mspvirajpatel/Xcode_Developer_Disk_Images/releases/tag/16.6 @KvassBoy
