### ISSUE TITLE
ios 14.4 developer image ?

### ISSUE THREAD

**Issue by Dantee296** [mspvirajpatel/Xcode_Developer_Disk_Images#6]
Hey guys can anyone provide 14.4 developer image ?

**Comment by somanas** [comment]
Did you manage to find the image ?

**Comment by Dantee296** [comment]
https://github.com/haikieu/xcode-developer-disk-image-all-platforms/pull/4
@somanas

**Comment by mspvirajpatel** [comment]
Download from this link @Dantee296 @somanas 
https://github.com/mspvirajpatel/Xcode_Developer_Disk_Images/releases/tag/14.4
